"""Every way of writing the subtitles config must work, or fail loudly.

``filterseries()`` sets ``ser['subtitles'] = True`` whenever the key appears,
but fills ``subtitles_languages`` / ``subtitles_autogenerated`` only when their
sub-keys are present. ``download_options()`` read both with bare indexing, so
three of the four realistic shapes raised ``KeyError`` -- including
``subtitles: true``, the obvious way to turn them on.

That was not a skipped episode. ``download_options()`` is called outside the
``try`` in ``download_episode()``, so the KeyError propagated through
``download()`` into ``main()`` and killed the process the moment a matching
episode was found.

A second, quieter failure sat next to it: ``subtitleslangs`` is iterated by
yt-dlp, so a scalar ``languages: en`` was read as the characters 'e' and 'n',
matched nothing, and downloaded no subtitles without raising.

Note ``subtitles: true`` reaches the first bug by two routes. Under
``yaml.BaseLoader`` the value is the string ``'true'``, so the
``'languages' in wnt['subtitles']`` guard in filterseries() is a *substring*
test against ``'true'`` rather than a dict lookup, and is False.
"""
import os
import sys
import unittest

APP_DIR = os.path.abspath(os.path.join(os.path.dirname(__file__), '..', 'app'))
sys.path.insert(0, APP_DIR)

os.environ.setdefault('CONFIGPATH', os.path.join(APP_DIR, '..', 'config', 'config.yml'))
os.makedirs(os.path.join(APP_DIR, '..', 'logs'), exist_ok=True)
sys.argv = sys.argv[:1]

import stream_harvestarr as app  # noqa: E402

EPISODE = {'title': 'Episode', 'seasonNumber': 1, 'episodeNumber': 1}


def options_for(**series_extras):
    """Build download options for a series with these subtitle settings."""
    client = object.__new__(app.StreamHarvester)
    client.ytdl_format = 'best'
    client.ytdl_merge_output_format = 'mkv'
    client.root_folder = ''
    client.season_padding = client.episode_padding = 0
    client.sleep_requests = 0
    client.debug = False
    series = {'id': 1, 'title': 'Show', 'path': '/tv/Show', **series_extras}
    return client.download_options(series, dict(EPISODE))


class SubtitleConfigShapeTests(unittest.TestCase):

    def test_no_shape_raises(self):
        """Every realistic config shape must build options without raising."""
        shapes = {
            'subtitles: true': {'subtitles': True},
            'languages only (list)': {
                'subtitles': True, 'subtitles_languages': ['en']},
            'languages only (scalar)': {
                'subtitles': True, 'subtitles_languages': 'en'},
            'autogenerated only': {
                'subtitles': True, 'subtitles_autogenerated': 'true'},
            'both': {
                'subtitles': True, 'subtitles_languages': ['en'],
                'subtitles_autogenerated': 'true'},
            'subtitles disabled': {},
        }
        for label, extras in shapes.items():
            with self.subTest(shape=label):
                options_for(**extras)  # must not raise

    def test_languages_absent_leaves_selection_to_ytdlp(self):
        """Do not guess a language; yt-dlp prefers en and falls back sensibly."""
        options = options_for(subtitles=True)
        self.assertTrue(options['writesubtitles'])
        self.assertNotIn(
            'subtitleslangs', options,
            'hardcoding a language would download nothing on a channel that '
            'has no subtitles in it; yt-dlp picks en, then en*, then the '
            'first available.')

    def test_scalar_language_is_wrapped_into_a_list(self):
        """A bare 'en' must not be iterated as the characters e and n."""
        self.assertEqual(options_for(
            subtitles=True, subtitles_languages='en')['subtitleslangs'], ['en'])

    def test_list_languages_are_passed_through(self):
        self.assertEqual(options_for(
            subtitles=True,
            subtitles_languages=['en', 'es'])['subtitleslangs'], ['en', 'es'])

    def test_autogenerated_accepts_yaml_strings_and_native_booleans(self):
        """checkconfig() parses with BaseLoader, so 'False' is a truthy string.

        A bare truth test here would enable autogenerated subtitles for
        exactly the users who wrote the key to turn them off. Native booleans
        have to work too -- that is what #124 needed.
        """
        for value, expected in (
            ('true', True), ('True', True), ('t', True), ('y', True),
            ('yes', True), (True, True),
            ('false', False), ('False', False), ('no', False), (False, False),
        ):
            with self.subTest(value=value):
                self.assertIs(
                    options_for(subtitles=True,
                                subtitles_autogenerated=value)['writeautomaticsub'],
                    expected)

    def test_autogenerated_defaults_off_when_unset(self):
        self.assertIs(options_for(subtitles=True)['writeautomaticsub'], False)

    def test_subtitle_postprocessors_are_installed(self):
        """The convert + embed pair is the point of enabling subtitles."""
        keys = [p['key'] for p in options_for(subtitles=True)['postprocessors']]
        self.assertIn('FFmpegSubtitlesConvertor', keys)
        self.assertIn('FFmpegEmbedSubtitle', keys)

    def test_disabled_subtitles_add_no_subtitle_options(self):
        """The default path must be untouched by any of this."""
        options = options_for()
        for key in ('writesubtitles', 'writeautomaticsub', 'subtitleslangs',
                    'postprocessors'):
            self.assertNotIn(key, options)


if __name__ == '__main__':
    unittest.main()
