"""
Unit tests for the ``strict_parts`` opt-in.

Refusing a "Part N" upload for an episode Sonarr models as whole is the
*correct* behaviour — part 1 downloads, ``hasFile`` flips, and parts 2-5 are
never fetched, so the episode looks complete and is a fragment. But it is not
the behaviour existing libraries were built against: on a real 53-episode
measurement 17 episodes stop matching, and a user experiences that as a third
of their library going missing after an update rather than as a fix. So it is
opt-in, defaulting to the historical behaviour, and the default can flip in a
later major release.

The load-bearing test here is the coercion one. ``checkconfig()`` parses with
``yaml.BaseLoader``, so ``strict_parts: False`` arrives as the *string*
``'False'`` — which is truthy. A bare truth test would enable the flag for
precisely the users who wrote it to opt out. The native ``True`` has to be
accepted too, which is the direction #124 fixed for ``subtitles_autogenerated``.
"""
import os
import sys
import unittest

APP_DIR = os.path.abspath(os.path.join(os.path.dirname(__file__), '..', 'app'))
sys.path.insert(0, APP_DIR)

# stream_harvestarr reads CONFIGPATH and parses argv at import time.
os.environ.setdefault('CONFIGPATH', os.path.join(APP_DIR, '..', 'config', 'config.yml'))
os.makedirs(os.path.join(APP_DIR, '..', 'logs'), exist_ok=True)
sys.argv = sys.argv[:1]

import stream_harvestarr  # noqa: E402
from stream_harvestarr import parts_allowed  # noqa: E402


class TestPartsAllowed(unittest.TestCase):
    """The flag decides whether Sonarr's title gates part candidates."""

    def test_off_permits_a_part_for_a_whole_episode(self):
        """The historical behaviour, kept as the default."""
        self.assertTrue(parts_allowed('Ricky Oyola', False))

    def test_on_refuses_a_part_for_a_whole_episode(self):
        self.assertFalse(parts_allowed('Ricky Oyola', True))

    def test_on_permits_a_part_for_a_part_episode(self):
        self.assertTrue(parts_allowed('Ricky Oyola (Part 1/5)', True))

    def test_off_permits_a_part_for_a_part_episode(self):
        self.assertTrue(parts_allowed('Ricky Oyola (Part 1/5)', False))

    def test_none_is_off(self):
        """ser.get('strict_parts') yields None if the default never ran."""
        self.assertTrue(parts_allowed('Ricky Oyola', None))


class TestStrictPartsConfigCoercion(unittest.TestCase):
    """yaml.BaseLoader hands every scalar over as a string."""

    def filterseries(self, series_entry):
        harvester = stream_harvestarr.StreamHarvester.__new__(
            stream_harvestarr.StreamHarvester)
        entry = {'title': 'Some Series', 'url': 'https://x/'}
        entry.update(series_entry)
        harvester.series = [entry]
        harvester.services = {}
        harvester.get_series = lambda: [{
            'title': 'Some Series', 'id': 1, 'monitored': True, 'path': '/tv/some'}]
        return stream_harvestarr.StreamHarvester.filterseries(harvester)[0]

    def test_absent_defaults_to_off(self):
        self.assertFalse(self.filterseries({})['strict_parts'])

    def test_string_false_stays_off(self):
        """The regression this flag would otherwise ship: 'False' is truthy."""
        self.assertFalse(self.filterseries({'strict_parts': 'False'})['strict_parts'])

    def test_lowercase_string_false_stays_off(self):
        self.assertFalse(self.filterseries({'strict_parts': 'false'})['strict_parts'])

    def test_string_true_enables(self):
        self.assertTrue(self.filterseries({'strict_parts': 'True'})['strict_parts'])

    def test_lowercase_string_true_enables(self):
        self.assertTrue(self.filterseries({'strict_parts': 'true'})['strict_parts'])

    def test_real_boolean_true_enables(self):
        """A caller that bypasses BaseLoader still works."""
        self.assertTrue(self.filterseries({'strict_parts': True})['strict_parts'])

    def test_garbage_does_not_enable(self):
        """Only an affirmative spelling opts in; anything else is off."""
        self.assertFalse(self.filterseries({'strict_parts': 'yes'})['strict_parts'])


class TestStrictPartsIsInheritable(unittest.TestCase):
    """A service can set it once instead of every series repeating it."""

    def merged(self, series_entry, service_entry):
        harvester = stream_harvestarr.StreamHarvester.__new__(
            stream_harvestarr.StreamHarvester)
        harvester.services = {'svc': dict(
            {'title': 'svc', 'url': 'https://example.com'}, **service_entry)}
        entry = {'title': 'S', 'service': 'svc', 'url': '/path'}
        entry.update(series_entry)
        return stream_harvestarr.StreamHarvester.merge_service_config(harvester, entry)

    def test_inherited_from_the_service(self):
        self.assertEqual(
            self.merged({}, {'strict_parts': 'True'})['strict_parts'], 'True')

    def test_series_overrides_the_service(self):
        self.assertEqual(
            self.merged({'strict_parts': 'False'},
                        {'strict_parts': 'True'})['strict_parts'], 'False')

    def test_inherited_value_is_still_coerced(self):
        """Inheritance must not smuggle a raw string past the coercion."""
        harvester = stream_harvestarr.StreamHarvester.__new__(
            stream_harvestarr.StreamHarvester)
        harvester.services = {'svc': {
            'title': 'svc', 'url': 'https://x', 'strict_parts': 'False'}}
        harvester.series = [{'title': 'Some Series', 'service': 'svc', 'url': 'https://x/'}]
        harvester.get_series = lambda: [{
            'title': 'Some Series', 'id': 1, 'monitored': True, 'path': '/tv/some'}]
        ser = stream_harvestarr.StreamHarvester.filterseries(harvester)[0]
        self.assertFalse(ser['strict_parts'])


class TestStrictPartsIsARecognisedKey(unittest.TestCase):
    """It must not trip the unrecognised-key warning this PR added."""

    def warn(self, entries, known):
        msgs = []
        original = stream_harvestarr.logger.warning
        stream_harvestarr.logger.warning = lambda m: msgs.append(m)
        try:
            stream_harvestarr.warn_unknown_keys(entries, known, 'Series')
        finally:
            stream_harvestarr.logger.warning = original
        return msgs

    def test_accepted_on_a_series(self):
        self.assertEqual(self.warn(
            [{'title': 'S', 'url': 'u', 'strict_parts': 'True'}],
            stream_harvestarr.KNOWN_SERIES_KEYS), [])

    def test_accepted_on_a_service(self):
        self.assertEqual(self.warn(
            [{'title': 'svc', 'url': 'u', 'strict_parts': 'True'}],
            stream_harvestarr.KNOWN_SERVICE_KEYS), [])


class TestEndToEndMatching(unittest.TestCase):
    """The flag's whole point, at the level a user would describe it."""

    def matches(self, site_title, sonarr_title, strict_parts):
        return stream_harvestarr.episode_title_matches(
            site_title,
            stream_harvestarr.upperescape(sonarr_title),
            stream_harvestarr.MatchRules(
                allow_parts=parts_allowed(sonarr_title, strict_parts)),
        )

    def test_default_keeps_matching_a_part_upload(self):
        """Upgrading without touching config must not lose this match."""
        self.assertTrue(self.matches(
            "Epicly Later'd: Ricky Oyola (Part 1/5)", 'Ricky Oyola', False))

    def test_opt_in_refuses_the_part_upload(self):
        self.assertFalse(self.matches(
            "Epicly Later'd: Ricky Oyola (Part 1/5)", 'Ricky Oyola', True))

    def test_opt_in_still_matches_a_whole_upload(self):
        self.assertTrue(self.matches(
            "Epicly Later'd: Chima Ferguson", 'Chima Ferguson', True))

    def test_opt_in_matches_a_split_episode_per_part(self):
        """The documented remedy: one Sonarr episode per part."""
        self.assertTrue(self.matches(
            "Epicly Later'd: Ricky Oyola (Part 3/5)", 'Ricky Oyola (Part 3/5)', True))

    def test_opt_in_still_rejects_the_wrong_part(self):
        self.assertFalse(self.matches(
            "Epicly Later'd: Ricky Oyola (Part 4/5)", 'Ricky Oyola (Part 3/5)', True))


if __name__ == '__main__':
    unittest.main()
