name: Docker (ID Crisis)

on:
  workflow_dispatch:
  push:
    branches:
      - proj_id_crisis
    tags:
      - "*"
      
jobs:
  docker:
    name: Docker
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:

      # https://github.com/marketplace/actions/checkout
      - name: Checkout
        uses: actions/checkout@v4

      # https://github.com/docker/login-action#docker-hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Set Docker Tag
        id: tag
        run: |
          if [[ $GITHUB_REF == refs/heads/proj_id_crisis ]]; then
            DOCKER_TAG="id_crisis"
          else
            DOCKER_TAG="${GITHUB_REF:11}"
          fi
          echo "tag=${DOCKER_TAG}" >> $GITHUB_OUTPUT

      # https://github.com/MyAlbum/purge-cache
      - name: Purge Build Cache
        uses: MyAlbum/purge-cache@v2
        with:
          debug: true # turn on debug logging (default: false)
          max-age: 5400 # Leave only caches accessed/created in the last 90 minutes (default: 604800 - 7 days)

      # https://github.com/docker/setup-qemu-action
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      # https://github.com/docker/setup-buildx-action
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # https://github.com/docker/build-push-action
      - name: Build and Push Dev Docker Image
        if: github.ref == 'refs/heads/proj_id_crisis' || startsWith(github.ref, 'refs/tags/')
        id: docker_build_id
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          file: ./Dockerfile
          platforms: linux/386,linux/amd64
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/sonarr-yt-dlp:${{ steps.tag.outputs.tag }}
            ${{ secrets.DOCKER_USERNAME }}/stream-harvestarr:${{ steps.tag.outputs.tag }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max